#!/usr/bin/env python3
"""Merck PPTX Pipeline — Setup & Dependency Checker

Run this once after cloning or updating the repo:

  python setup_merck_pptx.py

What it does:
  1. Checks Python version (3.9+ required)
  2. Installs / verifies required pip packages
  3. Auto-detects the local empower installation
  4. Writes ~/.merck_pptx/config.yaml with the correct paths for this machine
  5. Runs a quick import smoke test

Supports Windows (primary), macOS, and Linux.
"""

from __future__ import annotations

import os
import pathlib
import platform
import subprocess
import sys

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MIN_PYTHON = (3, 9)

REQUIRED_PACKAGES = [
    "python-pptx>=0.6.21",
    "lxml>=4.9.0",
    "pyyaml>=6.0",
    "Pillow>=9.0",              # for image handling
    "pywin32>=306; sys_platform=='win32'",   # for COM automation (optional)
]

# Empower local cache path template — {localappdata} is expanded at runtime
EMPOWER_SUBPATH = "empower/data/empower"

CONFIG_TEMPLATE = """\
# Merck PPTX Pipeline — machine-specific configuration
# Generated by setup_merck_pptx.py on {hostname}
# DO NOT commit this file to git (it is gitignored).

empower:
  # Path to the empower BinaryFiles cache (contains per-slide PPTX assets).
  # Set enabled: false to disable all empower integration.
  enabled: {empower_enabled}
  binary_dir:    "{binary_dir}"
  thumbnail_dir: "{thumbnail_dir}"

# To override paths on a different machine, edit this file or re-run setup.
# Supported variables: {{username}}, {{home}}, {{appdata}}, {{localappdata}}
# Example portable path:
#   binary_dir: "{{localappdata}}/empower/data/empower/BinaryFiles"
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _sep(char="-", width=60):
    print(char * width)


def _header(title: str):
    _sep()
    print(f"  {title}")
    _sep()


def _ok(msg: str):
    print(f"  [OK]   {msg}")


def _warn(msg: str):
    print(f"  [WARN] {msg}")


def _fail(msg: str):
    print(f"  [FAIL] {msg}")


# ---------------------------------------------------------------------------
# Step 1: Python version
# ---------------------------------------------------------------------------

def check_python():
    _header("Step 1 — Python version")
    v = sys.version_info[:2]
    if v < MIN_PYTHON:
        _fail(f"Python {v[0]}.{v[1]} detected — {MIN_PYTHON[0]}.{MIN_PYTHON[1]}+ required.")
        sys.exit(1)
    _ok(f"Python {v[0]}.{v[1]}.{sys.version_info[2]}  ({sys.executable})")


# ---------------------------------------------------------------------------
# Step 2: Install packages
# ---------------------------------------------------------------------------

def install_packages():
    _header("Step 2 — Python packages")
    pip = [sys.executable, "-m", "pip", "install", "--quiet", "--upgrade"]
    for pkg in REQUIRED_PACKAGES:
        name = pkg.split(">=")[0].split(";")[0].strip()
        try:
            result = subprocess.run(
                pip + [pkg],
                capture_output=True, text=True, check=True
            )
            _ok(f"{name} installed/verified")
        except subprocess.CalledProcessError as e:
            _warn(f"{name} — install failed: {e.stderr.strip()[:80]}")


# ---------------------------------------------------------------------------
# Step 3: Detect empower
# ---------------------------------------------------------------------------

def detect_empower() -> tuple[bool, str, str]:
    """Return (found, binary_dir, thumbnail_dir)."""
    _header("Step 3 — empower local cache detection")

    if platform.system() == "Windows":
        localappdata = os.environ.get(
            "LOCALAPPDATA",
            str(pathlib.Path.home() / "AppData" / "Local")
        )
    else:
        # macOS / Linux: empower is Windows-only, but allow override via env
        localappdata = os.environ.get(
            "LOCALAPPDATA",
            str(pathlib.Path.home() / ".local")
        )

    empower_root  = pathlib.Path(localappdata) / "empower" / "data" / "empower"
    binary_dir    = empower_root / "BinaryFiles"
    thumbnail_dir = empower_root / "ThumbnailLarge"

    if empower_root.exists():
        n_binary    = len(list(binary_dir.glob("*.pptx"))) if binary_dir.exists() else 0
        n_thumbnail = len(list(thumbnail_dir.glob("*.jpg"))) if thumbnail_dir.exists() else 0
        _ok(f"empower cache found: {empower_root}")
        _ok(f"  BinaryFiles:    {n_binary} PPTX files")
        _ok(f"  ThumbnailLarge: {n_thumbnail} thumbnails")
        return True, str(binary_dir), str(thumbnail_dir)
    else:
        _warn(f"empower cache not found at: {empower_root}")
        _warn("  Cover shape morphology will use the default template shapes.")
        _warn("  Install the empower PowerPoint add-in to enable this feature:")
        _warn("  https://evarooms.merckgroup.com/Topic/MerckBrandCMB")
        return False, str(binary_dir), str(thumbnail_dir)


# ---------------------------------------------------------------------------
# Step 4: Write config.yaml
# ---------------------------------------------------------------------------

def write_config(empower_found: bool, binary_dir: str, thumbnail_dir: str):
    _header("Step 4 — Writing config.yaml (project root, gitignored)")

    # Write to the project root so the pipeline finds it automatically.
    # The file is gitignored — each machine generates its own.
    project_root = pathlib.Path(__file__).parent
    config_path  = project_root / "config.yaml"

    content = CONFIG_TEMPLATE.format(
        hostname      = platform.node(),
        empower_enabled = "true" if empower_found else "false",
        binary_dir    = binary_dir.replace("\\", "/"),
        thumbnail_dir = thumbnail_dir.replace("\\", "/"),
    )

    config_path.write_text(content, encoding="utf-8")
    _ok(f"Config written to: {config_path}")
    print()
    print("  Contents:")
    for line in content.splitlines():
        print(f"    {line}")


# ---------------------------------------------------------------------------
# Step 5: Import smoke test
# ---------------------------------------------------------------------------

def smoke_test():
    _header("Step 5 — Import smoke test")
    try:
        import merck_pptx
        _ok("merck_pptx imported successfully")
    except ImportError as e:
        _fail(f"merck_pptx import failed: {e}")
        _warn("  Run from the repo root: python setup_merck_pptx.py")
        return

    try:
        from merck_pptx.config import get_config
        cfg = get_config()
        _ok(f"Config loaded — empower enabled: {cfg.get('empower', {}).get('enabled')}")
    except Exception as e:
        _warn(f"Config load warning: {e}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print()
    print("  Merck PPTX Pipeline — Setup")
    print(f"  Platform: {platform.system()} {platform.release()}  ({platform.node()})")
    print(f"  User:     {os.environ.get('USERNAME') or os.environ.get('USER', 'unknown')}")
    print()

    check_python()
    install_packages()
    empower_found, binary_dir, thumbnail_dir = detect_empower()
    write_config(empower_found, binary_dir, thumbnail_dir)
    smoke_test()

    _sep()
    print()
    print("  Setup complete.")
    print("  Run 'python -m merck_pptx build plan.json output.pptx' to generate a deck.")
    print()


if __name__ == "__main__":
    main()
