#!/usr/bin/env python3
"""Merck PPTX Pipeline — Setup & Dependency Checker

Run this once after cloning or updating the repo:

  python setup_merck_pptx.py

What it does:
  1. Checks Python version (3.9+ required)
  2. Installs / verifies required pip packages
  3. Auto-detects the local empower installation
  4. Writes ~/.merck_pptx/config.yaml with the correct paths for this machine
  5. Runs a quick import smoke test

Supports Windows (primary), macOS, and Linux.
"""

from __future__ import annotations

import os
import pathlib
import platform
import subprocess
import sys

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MIN_PYTHON = (3, 9)

REQUIRED_PACKAGES = [
    "python-pptx>=0.6.21",
    "lxml>=4.9.0",
    "pyyaml>=6.0",
    "Pillow>=9.0",              # for image handling
    "pywin32>=306; sys_platform=='win32'",   # for COM automation (optional)
]

# Empower local cache path template — {localappdata} is expanded at runtime
EMPOWER_SUBPATH = "empower/data/empower"

CONFIG_TEMPLATE_EMPOWER = """\
# Merck PPTX Pipeline — machine-specific configuration
# Generated by setup_merck_pptx.py on {hostname}
# DO NOT commit this file to git (it is gitignored).

empower:
  # Path to the empower BinaryFiles cache (contains per-theme PPTX assets).
  # Set enabled: false to disable all empower integration.
  enabled: true
  binary_dir:    "{binary_dir}"
  thumbnail_dir: "{thumbnail_dir}"

manual_templates:
  # Optional override for the user-managed template folder.
  # Leave empty (dir: "") to use the default: ~/.merck_pptx/templates/
  dir: ""

# To override paths on a different machine, edit this file or re-run setup.
# Supported variables: {{username}}, {{home}}, {{appdata}}, {{localappdata}}
# Example portable path:
#   binary_dir: "{{localappdata}}/empower/data/empower/BinaryFiles"
"""

CONFIG_TEMPLATE_NO_EMPOWER = """\
# Merck PPTX Pipeline — machine-specific configuration
# Generated by setup_merck_pptx.py on {hostname}
# DO NOT commit this file to git (it is gitignored).

empower:
  enabled: false

manual_templates:
  # Place template files here as {{division}}_{{color_theme}}.pptx
  # e.g. merck_organic.pptx, emd_serono_plastic.pptx
  # Default location: ~/.merck_pptx/templates/  (leave dir: "" to use it)
  dir: ""
"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _sep(char="-", width=60):
    print(char * width)


def _header(title: str):
    _sep()
    print(f"  {title}")
    _sep()


def _ok(msg: str):
    print(f"  [OK]   {msg}")


def _warn(msg: str):
    print(f"  [WARN] {msg}")


def _fail(msg: str):
    print(f"  [FAIL] {msg}")


# ---------------------------------------------------------------------------
# Step 1: Python version
# ---------------------------------------------------------------------------

def check_python():
    _header("Step 1 — Python version")
    v = sys.version_info[:2]
    if v < MIN_PYTHON:
        _fail(f"Python {v[0]}.{v[1]} detected — {MIN_PYTHON[0]}.{MIN_PYTHON[1]}+ required.")
        sys.exit(1)
    _ok(f"Python {v[0]}.{v[1]}.{sys.version_info[2]}  ({sys.executable})")


# ---------------------------------------------------------------------------
# Step 2: Install packages
# ---------------------------------------------------------------------------

def install_packages():
    _header("Step 2 — Python packages")
    pip = [sys.executable, "-m", "pip", "install", "--quiet", "--upgrade"]
    for pkg in REQUIRED_PACKAGES:
        name = pkg.split(">=")[0].split(";")[0].strip()
        try:
            result = subprocess.run(
                pip + [pkg],
                capture_output=True, text=True, check=True
            )
            _ok(f"{name} installed/verified")
        except subprocess.CalledProcessError as e:
            _warn(f"{name} — install failed: {e.stderr.strip()[:80]}")


# ---------------------------------------------------------------------------
# Step 3: Detect empower
# ---------------------------------------------------------------------------

def detect_empower() -> tuple[bool, str, str]:
    """Return (found, binary_dir, thumbnail_dir)."""
    _header("Step 3 — empower local cache detection")

    if platform.system() == "Windows":
        localappdata = os.environ.get(
            "LOCALAPPDATA",
            str(pathlib.Path.home() / "AppData" / "Local")
        )
    else:
        # macOS / Linux: empower is Windows-only, but allow override via env
        localappdata = os.environ.get(
            "LOCALAPPDATA",
            str(pathlib.Path.home() / ".local")
        )

    empower_root  = pathlib.Path(localappdata) / "empower" / "data" / "empower"
    binary_dir    = empower_root / "BinaryFiles"
    thumbnail_dir = empower_root / "ThumbnailLarge"

    if empower_root.exists():
        n_binary    = len(list(binary_dir.glob("*.pptx"))) if binary_dir.exists() else 0
        n_thumbnail = len(list(thumbnail_dir.glob("*.jpg"))) if thumbnail_dir.exists() else 0
        _ok(f"empower cache found: {empower_root}")
        _ok(f"  BinaryFiles:    {n_binary} PPTX files")
        _ok(f"  ThumbnailLarge: {n_thumbnail} thumbnails")
        return True, str(binary_dir), str(thumbnail_dir)
    else:
        _warn(f"empower not found at: {empower_root}")
        _warn("  BinaryFile templates are unavailable on this machine.")
        print()
        print("  For Mac/Linux users (or Windows without empower):")
        print("  You can download individual templates manually instead.")
        print()
        manual_dir = pathlib.Path.home() / ".merck_pptx" / "templates"
        print(f"  1. Ask a Windows colleague to export a template from PowerPoint:")
        print( "       empower tab -> Corporate Design Templates -> Master Templates")
        print( "       Right-click a template -> Export to file -> save as .pptx")
        print()
        print(f"  2. Place the file in:  {manual_dir}")
        print( "     Named as:           {{division}}_{{color_theme}}.pptx")
        print( "     Examples:           merck_organic.pptx")
        print( "                         emd_serono_plastic.pptx")
        print()
        print( "  3. Re-run this setup to confirm the template is recognised.")
        print()
        print( "  Valid division keys:    merck  merck_asia  emd_serono")
        print( "                          millipore_sigma  emd_electronics  usa")
        print( "  Valid color_theme keys: plastic  functional  organic")
        print( "                          synthetic  technical  electronics")
        print()
        print( "  Note: division='merck' works without any download -- the bundled")
        print( "  EU_Merck_Themed.pptx / USA_Merck_Themed_Base_v1.pptx cover all")
        print( "  6 color themes for the 'merck' division out of the box.")
        return False, str(binary_dir), str(thumbnail_dir)


# ---------------------------------------------------------------------------
# Step 4: Write config.yaml
# ---------------------------------------------------------------------------

def write_config(empower_found: bool, binary_dir: str, thumbnail_dir: str):
    _header("Step 4 — Writing config.yaml (project root, gitignored)")

    # Write to the project root so the pipeline finds it automatically.
    # The file is gitignored — each machine generates its own.
    project_root = pathlib.Path(__file__).parent
    config_path  = project_root / "config.yaml"

    if empower_found:
        content = CONFIG_TEMPLATE_EMPOWER.format(
            hostname      = platform.node(),
            binary_dir    = binary_dir.replace("\\", "/"),
            thumbnail_dir = thumbnail_dir.replace("\\", "/"),
        )
    else:
        content = CONFIG_TEMPLATE_NO_EMPOWER.format(
            hostname = platform.node(),
        )

    config_path.write_text(content, encoding="utf-8")
    _ok(f"Config written to: {config_path}")
    print()
    print("  Contents:")
    for line in content.splitlines():
        print(f"    {line}")


# ---------------------------------------------------------------------------
# Step 5: Scan available templates
# ---------------------------------------------------------------------------

def scan_available_templates(binary_dir_str: str, empower_found: bool):
    """Print a catalogue of every template available on this machine."""
    _header("Step 5 — Available templates")

    bundled_count = 0
    empower_count = 0
    manual_count  = 0

    # ---- bundled ---------------------------------------------------------
    print("  [bundled]  -- always available, no download needed")
    try:
        # Access the package templates directory relative to this script
        pkg_dir = pathlib.Path(__file__).parent / "merck_pptx" / "templates"
        eu_ok  = (pkg_dir / "EU_Merck_Themed.pptx").exists()
        usa_ok = (pkg_dir / "USA_Merck_Themed_Base_v1.pptx").exists()
        if eu_ok:
            _ok("eu  / merck  ->  EU_Merck_Themed.pptx  (all 6 color themes)")
            bundled_count += 1
        else:
            _fail("eu  / merck  ->  EU_Merck_Themed.pptx  NOT FOUND (package incomplete)")
        if usa_ok:
            _ok("usa / merck  ->  USA_Merck_Themed_Base_v1.pptx  (all 6 color themes)")
            bundled_count += 1
        else:
            _warn("usa / merck  ->  USA_Merck_Themed_Base_v1.pptx  not present")
        print("       (color themes are applied programmatically -- no separate")
        print("        file is needed per theme for the 'merck' division)")
    except Exception as exc:
        _warn(f"Could not check bundled templates: {exc}")

    # ---- empower ---------------------------------------------------------
    print()
    if not empower_found:
        print("  [empower BinaryFiles]  NOT FOUND -- empower is not installed")
        print("    (see instructions above for the manual download alternative)")
    else:
        binary_dir = pathlib.Path(binary_dir_str)
        print(f"  [empower BinaryFiles]  --  {binary_dir}")
        try:
            from merck_pptx.binary_templates import load_registry, uid_to_path
            from merck_pptx.manual_templates import VALID_THEMES as _ALL_THEMES
            registry = load_registry()
            if not registry:
                _warn("Registry is empty -- run 'python -m merck_pptx discover-templates'")
            else:
                for div, themes in sorted(registry.items()):
                    if div.startswith("_") or not isinstance(themes, dict):
                        continue
                    present = []
                    missing = []
                    for theme in _ALL_THEMES:
                        uid = themes.get(theme)
                        if uid:
                            p = uid_to_path(uid)
                            if p is not None:
                                present.append(theme)
                            else:
                                missing.append(theme + "(!)")
                    if present:
                        _ok(f"{div:<22} {', '.join(present)}")
                        empower_count += len(present)
                    if missing:
                        _warn(f"{div:<22} {', '.join(missing)}  "
                              "(registered but file missing -- reinstall empower?)")
        except Exception as exc:
            _warn(f"Could not read empower registry: {exc}")

    # ---- manual ----------------------------------------------------------
    print()
    try:
        from merck_pptx.manual_templates import manual_templates_dir, list_manual_templates
        mdir = manual_templates_dir()
        print(f"  [manual]  --  {mdir}")
        manual = list_manual_templates()
        if not mdir.exists():
            print("    (directory does not exist yet -- create it to add templates)")
        elif not manual:
            print("    (no recognised .pptx files found)")
            print("    Name files as {division}_{color_theme}.pptx to add them here")
        else:
            for entry in manual:
                _ok(f"{entry['division']:<22} {entry['color_theme']:<12}  {pathlib.Path(entry['path']).name}")
                manual_count += 1
    except Exception as exc:
        _warn(f"Could not scan manual templates: {exc}")

    # ---- summary ---------------------------------------------------------
    print()
    total = bundled_count * 6 + empower_count + manual_count
    print(f"  Total: {bundled_count} bundled divisions (x6 themes)"
          f" + {empower_count} empower + {manual_count} manual"
          f" = {total} available template combination(s)")
    print()
    print("  Run anytime:  python -m merck_pptx list-templates")


# ---------------------------------------------------------------------------
# Step 6: Import smoke test
# ---------------------------------------------------------------------------

def smoke_test():
    _header("Step 6 — Import smoke test")
    try:
        import merck_pptx
        _ok("merck_pptx imported successfully")
    except ImportError as e:
        _fail(f"merck_pptx import failed: {e}")
        _warn("  Run from the repo root: python setup_merck_pptx.py")
        return

    try:
        from merck_pptx.config import get_config
        cfg = get_config()
        _ok(f"Config loaded — empower enabled: {cfg.get('empower', {}).get('enabled')}")
    except Exception as e:
        _warn(f"Config load warning: {e}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print()
    print("  Merck PPTX Pipeline — Setup")
    print(f"  Platform: {platform.system()} {platform.release()}  ({platform.node()})")
    print(f"  User:     {os.environ.get('USERNAME') or os.environ.get('USER', 'unknown')}")
    print()

    check_python()
    install_packages()
    empower_found, binary_dir, thumbnail_dir = detect_empower()
    write_config(empower_found, binary_dir, thumbnail_dir)
    scan_available_templates(binary_dir, empower_found)
    smoke_test()

    _sep()
    print()
    print("  Setup complete.")
    print("  Run 'python -m merck_pptx build plan.json output.pptx' to generate a deck.")
    print("  Run 'python -m merck_pptx list-templates' to see available templates.")
    print()


if __name__ == "__main__":
    main()
